site_name: Root docs
repo_url: https://github.com/RoadieHQ/sample-service
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Local development: local-development.md
  - Feature Testing: feature-testing.md
  - TestDoc: test-doc.md
  - Embedded Lucid Chart: testing-lucid.md
  - Subdirectory docs: "!include ./sub-dir-documentation/mkdocs.yml"
  - Runbook: runbook.md

docs_dir: docs
plugins:
  - techdocs-core

markdown_extensions:
  - mkdocs_graphviz

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
