site_name: Root docs

nav:
  - Home: index.md
  - Local development: local-development.md
  - Feature Testing: feature-testing.md
  - Big ToC: big-table-of-contents.md
  - TestDoc: test-doc.md
  - Subdirectory docs:
    - mycomponent: '!include ./sub-dir-documentation/mkdocs.yml'

docs_dir: docs
plugins:
  - monorepo
  - techdocs-core
